In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import re
import string

In [3]:
data_fake = pd.read_csv('Fake.csv')
data_true = pd.read_csv('True.csv')

In [5]:
data_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [6]:
data_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [7]:
data_fake["class"] = 0
data_true["class"] = 1

In [8]:
data_fake.shape, data_true.shape

((23481, 5), (21417, 5))

In [8]:
data_fake.shape, data_true.shape

((23481, 5), (21417, 5))

In [34]:
print(data_fake.tail())
print(data_true.tail())

                                                   title  \
23466  Boston Brakes? How to Hack a New Car With Your...
23467  Oregon Governor Says Feds ‘Must Act’ Against P...
23468  Ron Paul on Burns Oregon Standoff and Jury Nul...
23469     BOILER ROOM: As the Frogs Slowly Boil – EP #40
23470  Arizona Rancher Protesting in Oregon is Target...

                                                    text      subject  \
23466  21st Century Wire says For those who still ref...  Middle-east
23467  21st Century Wire says So far, after nearly 20...  Middle-east
23468  21st Century Wire says If you ve been followin...  Middle-east
23469  Tune in to the Alternate Current Radio Network...  Middle-east
23470  RTOne of the most visible members of the armed...  Middle-east

                   date  class
23466  January 22, 2016      0
23467  January 21, 2016      0
23468  January 21, 2016      0
23469  January 20, 2016      0
23470  January 20, 2016      0
                                                   title  \
21402  Exclusive: Trump's Afghan decision may increas...
21403  U.S. puts more pressure on Pakistan to help wi...
21404  Exclusive: U.S. to withhold up to $290 million...
21405  Trump talks tough on Pakistan's 'terrorist' ha...
21406  U.S., North Korea clash at U.N. forum over nuc...

                                                    text    subject  \
21402  ON BOARD A U.S. MILITARY AIRCRAFT (Reuters) - ...  worldnews
21403  WASHINGTON (Reuters) - The United States sugge...  worldnews
21404  WASHINGTON (Reuters) - The United States has d...  worldnews
21405  ISLAMABAD (Reuters) - Outlining a new strategy...  worldnews
21406  GENEVA (Reuters) - North Korea and the United ...  worldnews

                   date  class
21402  August 22, 2017       1
21403  August 21, 2017       1
21404  August 22, 2017       1
21405  August 22, 2017       1
21406  August 22, 2017       1

In [35]:
print(data_fake.index[-10:])
print(data_true.index[-10:])

RangeIndex(start=23461, stop=23471, step=1)
RangeIndex(start=21397, stop=21407, step=1)

In [39]:
data_fake_manual_testing = data_fake.tail(10)

for i in range(23460, 23470, -1):
    data_fake.drop([i], axis = 0, inplace = True)

data_true_manual_testing = data_true.tail(10)

for i in range(21396, 21406, -1):
    data_true.drop([i], axis = 0, inplace = True)

In [40]:
data_fake.shape, data_true.shape

((23471, 5), (21407, 5))

In [41]:
data_fake_manual_testing['class'] = 0
data_true_manual_testing['class'] = 1

C:\Users\DELL\AppData\Local\Temp\ipykernel_22228\277247672.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_fake_manual_testing['class'] = 0
C:\Users\DELL\AppData\Local\Temp\ipykernel_22228\277247672.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_true_manual_testing['class'] = 1

In [44]:
data_fake_manual_testing.head(10)

,title,text,subject,date,class
23461,REPORT: ‘Federal Government Escalated the Viol...,KILLED: Rancher and protest spokesman Robert ...,Middle-east,"January 28, 2016",0
23462,"BOILER ROOM – Oregon Standoff, Cuddle Parties,...",Tune in to the Alternate Current Radio Network...,Middle-east,"January 28, 2016",0
23463,"Eyewitness Says Feds Ambushed Bundys, 100 Shot...",Patrick Henningsen 21st Century Wire UPDATE: 1...,Middle-east,"January 27, 2016",0
23464,Episode #119 – SUNDAY WIRE: ‘You Know the Dril...,Episode #119 of SUNDAY WIRE SHOW finally resum...,Middle-east,"January 24, 2016",0
23465,‘There’ll be boots on the ground’: US making n...,21st Century Wire says Various parties in Wash...,Middle-east,"January 23, 2016",0
23466,Boston Brakes? How to Hack a New Car With Your...,21st Century Wire says For those who still ref...,Middle-east,"January 22, 2016",0
23467,Oregon Governor Says Feds ‘Must Act’ Against P...,"21st Century Wire says So far, after nearly 20...",Middle-east,"January 21, 2016",0
23468,Ron Paul on Burns Oregon Standoff and Jury Nul...,21st Century Wire says If you ve been followin...,Middle-east,"January 21, 2016",0
23469,BOILER ROOM: As the Frogs Slowly Boil – EP #40,Tune in to the Alternate Current Radio Network...,Middle-east,"January 20, 2016",0
23470,Arizona Rancher Protesting in Oregon is Target...,RTOne of the most visible members of the armed...,Middle-east,"January 20, 2016",0

In [45]:
data_true_manual_testing.head(10)

,title,text,subject,date,class
21397,Germany's Schulz says he would demand U.S. wit...,BERLIN (Reuters) - The leader of Germany s Soc...,worldnews,"August 23, 2017",1
21398,Blunt instrument? What a list of banned articl...,SHANGHAI (Reuters) - An old review of an acade...,worldnews,"August 23, 2017",1
21399,Saudi police release teenager detained for dan...,DUBAI (Reuters) - A 14-year-old boy who was de...,worldnews,"August 22, 2017",1
21400,"The People's Princess, Britons work to keep me...",LONDON (Reuters) - Abdul Daoud spilt most of t...,worldnews,"August 23, 2017",1
21401,"Argentina labor unions protest job losses, Mac...",BUENOS AIRES (Reuters) - Argentina s main labo...,worldnews,"August 22, 2017",1
21402,Exclusive: Trump's Afghan decision may increas...,ON BOARD A U.S. MILITARY AIRCRAFT (Reuters) - ...,worldnews,"August 22, 2017",1
21403,U.S. puts more pressure on Pakistan to help wi...,WASHINGTON (Reuters) - The United States sugge...,worldnews,"August 21, 2017",1
21404,Exclusive: U.S. to withhold up to $290 million...,WASHINGTON (Reuters) - The United States has d...,worldnews,"August 22, 2017",1
21405,Trump talks tough on Pakistan's 'terrorist' ha...,ISLAMABAD (Reuters) - Outlining a new strategy...,worldnews,"August 22, 2017",1
21406,"U.S., North Korea clash at U.N. forum over nuc...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1

In [46]:
data_merge = pd.concat([data_fake, data_true], axis = 0)
data_merge.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [47]:
data_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [48]:
data = data_merge.drop(['title', 'subject', 'date'], axis = 1)

In [49]:
data.isnull().sum()

text     0
class    0
dtype: int64

In [50]:
data = data.sample(frac = 1)

In [51]:
data.head()

                                                    text  class
7563   WASHINGTON (Reuters) - Democratic presidential...      1
10903  WASHINGTON (Reuters) - The Obama administratio...      1
7491   Hillary Clinton s recent appearance with Chris...      0
14420  The Democrat motto: Whatever it takes UPDATE: ...      0
6218   WELLINGTON (Reuters) - New Zealand accounting ...      1

In [52]:
data.reset_index(inplace = True)
data.drop(['index'], axis = 1, inplace = True)

In [53]:
data.columns

Index(['text', 'class'], dtype='object')

In [54]:
data.head()

                                                text  class
0  WASHINGTON (Reuters) - Democratic presidential...      1
1  WASHINGTON (Reuters) - The Obama administratio...      1
2  Hillary Clinton s recent appearance with Chris...      0
3  The Democrat motto: Whatever it takes UPDATE: ...      0
4  WELLINGTON (Reuters) - New Zealand accounting ...      1

In [56]:
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W", " ", text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

In [57]:
data['text'] = data['text'].apply(wordopt)

In [58]:
x = data['text']
y = data['class']

In [59]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [69]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(xv_train, y_train)

LogisticRegression()

In [70]:
pred_lr = LR.predict(xv_test)

In [71]:
LR.score(xv_test, y_test)

0.9859180035650624

In [73]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      5908
           1       0.98      0.99      0.99      5312

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [78]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
DT.fit(xv_train, y_train)

DecisionTreeClassifier()

In [76]:
pred_dt = DT.predict(xv_test)

In [79]:
DT.score(xv_test, y_test)

0.9961675579322639

In [80]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      5908
           1       0.98      0.99      0.99      5312

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [81]:
from sklearn.ensemble import GradientBoostingClassifier

GB = GradientBoostingClassifier(random_state = 0)
GB.fit(xv_train, y_train)

GradientBoostingClassifier(random_state=0)

In [84]:
pred_gb = GB.predict(xv_test)

In [85]:
GB.score(xv_test, y_test)

0.9950980392156863

In [86]:
print(classification_report(y_test, pred_gb))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      5908
           1       0.99      1.00      0.99      5312

    accuracy                           1.00     11220
   macro avg       1.00      1.00      1.00     11220
weighted avg       1.00      1.00      1.00     11220

In [87]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier()
RF.fit(xv_train, y_train)

RandomForestClassifier()

In [88]:
pred_rf = RF.predict(xv_test)

In [90]:
RF.score(xv_test, y_test)

0.9869875222816399

In [91]:
print(classification_report(y_test, pred_rf))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5908
           1       0.99      0.99      0.99      5312

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [109]:
def output_label(n):
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Not a Fake News"

def manual_testing(news):
    testing_news = {"text":[news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(wordopt)
    new_x_test = new_def_test["text"]
    new_xv_test = vectorization.transform(new_x_test)
    pred_LR = LR.predict(new_xv_test)
    pred_DT = DT.predict(new_xv_test)
    pred_GB = GB.predict(new_xv_test)
    pred_RF = RF.predict(new_xv_test)

    return print("\n\nLR Prediction: {} \nDT Prediction: {} \nGB Prediction: {} \nRF Prediction: {}".format(output_label(pred_LR[0]),
                                                                                                             output_label(pred_DT[0]),
                                                                                                             output_label(pred_GB[0]),
                                                                                                             output_label(pred_RF[0])))

In [110]:
news = str(input())
manual_testing(news)

 WASHINGTON (Reuters) - Alabama Secretary of State John Merrill said he will certify Democratic Senator-elect Doug Jones as winner on Thursday despite opponent Roy Mooreâ€™s challenge, in a phone call on CNN. Moore, a conservative who had faced allegations of groping teenage girls when he was in his 30s, filed a court challenge late on Wednesday to the outcome of a U.S. Senate election he unexpectedly lost.

LR Prediction: Not a Fake News
DT Prediction: Not a Fake News
GB Prediction: Not a Fake News
RF Prediction: Not a Fake News